"""Build docs/trust.md from a grid's call logs and the T10 audit files (labels, scores, checker audit).

    python scripts/build_trust_doc.py outputs/runs/t9-dev outputs/trust/t10

Run `python -m pipeline_agents.eval.critic_audit score outputs/trust/t10` first so scores.json is current.
"""

import json
import sys
from collections import Counter
from pathlib import Path

from pipeline_agents.eval.critic_audit import load_cases

STRATA = {
    "accept/tool_fail": "accepted, a tool failed",
    "accept/tools_pass": "accepted, no tool failed",
    "revise/tool_fail": "revised, a tool failed",
    "revise/tools_pass": "revised, no tool failed",
}


def first_sentence(text: str, limit: int = 220) -> str:
    text = " ".join(text.split())
    cut = text.find(". ")
    text = text[: cut + 1] if 0 < cut < limit else text
    return text if len(text) <= limit else text[: limit - 1] + "…"


def build(grid_dir: Path, audit_dir: Path) -> str:
    cases = {c.case_id: c for c in load_cases(grid_dir)}
    scores = json.loads((audit_dir / "scores.json").read_text())
    ref = scores["reference"]
    labels = {
        json.loads(line)["case_id"]: json.loads(line)
        for line in (audit_dir / "labels_reference.jsonl").read_text().splitlines()
    }
    checker = json.loads((audit_dir / "checker_audit.json").read_text())
    results = {
        json.loads(p.read_text())["run_id"]: json.loads(p.read_text()) for p in grid_dir.glob("*/result.json")
    }
    confidence = Counter(c.confidence for c in cases.values())
    decisions = Counter(c.decision for c in cases.values())
    conf = ref["confusion"]
    lo, hi = ref["kappa_ci"]
    st = ref["strata"]
    accepts, revise_fail = st["accept/tools_pass"], st["revise/tool_fail"]
    labelled_accepts = sum(v["labelled"] for k, v in st.items() if k.startswith("accept"))
    labelled_revisions = sum(v["labelled"] for k, v in st.items() if k.startswith("revise"))

    out = [
        "# Can the Critic and the checker be trusted?",
        "",
        f"Before tuning anything on the dev grid (`{grid_dir.name}`), two questions: does the Critic judge "
        "steps the way a careful reader would, and are the checker's failures real failures? Generated by "
        "`scripts/build_trust_doc.py` from the call logs and `outputs/trust/t10/`.",
        "",
        "## The Critic",
        "",
        f"The dev grid made **{len(cases)} Critic calls** ({decisions['accept']} accept, "
        f"{decisions['revise']} revise, {decisions.get('escalate', 0)} escalate). A stratified sample of "
        f"{ref['labelled']} was labelled blind, without the Critic's decision, by answering one question: "
        "*can later steps build on this step as it is?*",
        "",
        "| | value |",
        "|---|---|",
        f"| agreement with the labels | {ref['agreement']:.0%} ({ref['labelled']} cases) |",
        f"| Cohen's kappa [95% CI] | {ref['kappa']:.2f} [{lo:.2f}, {hi:.2f}] |",
        f"| too strict (step was fine, Critic asked for a revision) | {conf.get('ok->not_ok', 0)} |",
        f"| too lenient (step was wrong, Critic accepted) | {conf.get('not_ok->ok', 0)} |",
        f"| estimated too strict, all {ref['population']} calls | {ref['est_too_strict']:.0f} |",
        f"| estimated too lenient, all {ref['population']} calls | {ref['est_too_lenient']:.0f} |",
        "| Critic confidence | "
        + ", ".join(f"{k:g}: {v}" for k, v in sorted(confidence.items(), reverse=True))
        + " |",
        "",
        "Kappa near 0.3 is weak agreement. The estimates scale each stratum's error rate to its size among "
        f"all calls; the lenient estimate rests on {accepts['too_lenient']} of {accepts['labelled']} "
        "labelled accepts and is rough.",
        "",
        "| stratum | calls | labelled | agree | too strict | too lenient |",
        "|---|---|---|---|---|---|",
    ]
    for key, s in ref["strata"].items():
        out.append(
            f"| {STRATA.get(key, key)} | {s['population']} | {s['labelled']} | {s['agree']} | "
            f"{s['too_strict']} | {s['too_lenient']} |"
        )
    out += [
        "",
        "What the numbers say:",
        "",
        "- **The confidence score carries no information.** It is 1.0 on almost every call, so the rule "
        '"confidence below 0.5 goes to a human" never fires.',
        f"- **Too strict, mostly because of one tool.** {revise_fail['too_strict']} of the "
        f"{revise_fail['labelled']} revisions that followed a failed tool were not needed. The row-count "
        "check compared every step with the raw file, so after one step dropped "
        "the rows with a missing target (on purpose, and accepted), every later step was flagged again for "
        "the same 21% drop. A loader that kept the file's 114 empty lines was flagged as a duplicating join. "
        "Unneeded revisions use up the revision budget and then the single re-plan: the two `air-2` runs "
        "that stopped at step s3 in T9 ended that way.",
        "- **Too lenient where no tool looks.** The accepted mistakes are a `predict.py` that cannot "
        "read the real input (a headerless file read with a header, one-hot columns filled with zeros) and a "
        "wrong number (temperature left normalized). No validation tool runs on those steps, and the Critic "
        "does not execute the script.",
        "",
        "### Disagreements",
        "",
        "| case | step | Critic | label | the Critic said | why the label |",
        "|---|---|---|---|---|---|",
    ]
    for case_id, lab in labels.items():
        c = cases[case_id]
        if lab["label"] == c.critic_label:
            continue
        said = first_sentence(c.issues[0]) if c.issues else "(no issues)"
        out.append(
            f"| `{case_id}` | {c.step_id} | {c.decision} | {lab['label'].replace('_', ' ')} | "
            f"{said.replace('|', '/')} | {lab['why'].replace('|', '/')} |"
        )
    wrong = [r for r, a in checker.items() if a["verdict"] != "correct"]
    out += [
        "",
        "## The checker",
        "",
        f"Every failed cell of the grid was read by hand ({len(checker)} cells): the failing stage, its "
        f"detail, and the deliverable. **{len(checker) - len(wrong)} of {len(checker)} failures are real.**",
        "",
        "| run | failed stage | detail | verdict |",
        "|---|---|---|---|",
    ]
    for run_id, a in checker.items():
        r = results[run_id]
        stage = (r.get("checker") or {}).get("first_failure") or r["status"]
        out.append(f"| `{run_id}` | {stage} | {a['why'].replace('|', '/')} | {a['verdict']} |")
    out += [
        "",
        "One design note, not a bug: `honest_estimate` is two-sided, so a validation estimate that is too "
        "pessimistic (bike-1: validation 78 against holdout 61) fails like an optimistic one. In this grid "
        "it never decided an outcome, because the score failed first.",
        "",
        "## What changed",
        "",
        "- The row-count check now compares a step with the largest table of the closest earlier accepted "
        "step (the raw file only for the first steps), and a table that grew by exactly the raw file's empty "
        "lines passes with a note. Tests cover both, and the step test fails on the old comparison.",
        "",
        "## Limits",
        "",
        "- One labeller, labelled blind. With no second labeller, labeller error is not measured; the "
        "*why* column above makes every label checkable.",
        f"- The sample is stratified ({labelled_revisions} of {decisions['revise']} revisions, "
        f"{labelled_accepts} of {decisions['accept']} accepts), so the raw agreement over-weights revisions; "
        "the population estimates correct for that.",
        "- Only failures were audited. A pass that should have failed is possible where a trap is marked "
        "*score only* (see `docs/benchmark.md`).",
        "- The row-count fix is checked by tests, not yet by a re-run of the grid; that happens in T11.",
        "",
    ]
    return "\n".join(out)


def main() -> None:
    grid_dir, audit_dir = Path(sys.argv[1]), Path(sys.argv[2])
    Path("docs/trust.md").write_text(build(grid_dir, audit_dir))
    print("wrote docs/trust.md")


if __name__ == "__main__":
    main()
