"""Build docs/failure_taxonomy.md from every grid's runs plus the hand-read notes in outputs/trust/t12.

    python scripts/build_taxonomy_doc.py outputs/runs/t9-dev outputs/runs/t11-dev ...
        --cases outputs/trust/t12

Counts and examples come from the run files; the "what it means" and "what would fix it" lines come from
notes.json, written after reading the runs of that class.
"""

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

from pipeline_agents.analysis.failures import CATEGORIES, Failure, failures

TITLES = {
    "below_threshold": "The model is not good enough",
    "data_deleted_as_hygiene": "Cleaning deleted real data",
    "loop_exhausted_delivery": "The loop ran out on predict.py",
    "memory_limit": "Killed by the memory limit",
    "benchmark_defect": "The benchmark is wrong",
    "loop_exhausted_crash": "The loop ran out on a crash",
    "unit_ignored": "A documented unit was ignored",
    "repair_exhausted": "The baseline ran out of repairs",
    "loop_exhausted_tool": "The loop ran out arguing with a tool",
    "loop_exhausted_plan": "The new plan repeated the old weakness",
    "parse_failure": "A reply could not be parsed",
    "dishonest_estimate": "The estimate the run trusted was far off",
    "loop_exhausted_other": "Other stops for a human",
    "wrong_answer": "A wrong number, cause not yet read",
}


def _anchor(title: str) -> str:
    """GitHub's heading anchor: lowercase, punctuation dropped, spaces to hyphens."""
    return "".join(c for c in title.lower() if c.isalnum() or c in " -").replace(" ", "-")


def _example(rows: list[Failure]) -> Failure:
    """The case with the fullest evidence: the longest detail, so the example shows what it looked like."""
    return max(rows, key=lambda f: len(f.detail))


def build(grids: list[Path], cases: dict, notes: dict) -> str:
    found = failures(grids, cases)
    by_category: dict[str, list[Failure]] = defaultdict(list)
    for f in found:
        by_category[f.category].append(f)
    order = sorted(by_category, key=lambda c: -len(by_category[c]))
    total = len(found)
    runs = sum(len(list(g.glob("*/result.json"))) for g in grids)

    lines = [
        "# Failure taxonomy",
        "",
        f"Every failed run of every grid in this repository: **{total} failures out of {runs} runs** "
        f"({', '.join(g.name for g in grids)}). Each one is placed by what it recorded (stop reason, first "
        "failed checker stage, which answer key was wrong); the wrong answers were read by hand, once per "
        "key. Generated by `scripts/build_taxonomy_doc.py`.",
        "",
        "| class | runs | team | baseline | what it is |",
        "|---|---|---|---|---|",
    ]
    for category in order:
        rows = by_category[category]
        team = sum(1 for f in rows if f.arm != "baseline")
        lines.append(
            f"| [{TITLES.get(category, category)}](#{_anchor(TITLES.get(category, category))}) | "
            f"{len(rows)} | {team} | {len(rows) - team} | {CATEGORIES.get(category, '')} |"
        )
    lines += [
        "",
        "The classes fall into three kinds, and the split matters more than the counts:",
        "",
        "- **The agents' own mistakes**: a weak model, a crash they could not fix, a unit they ignored.",
        "- **The system's design**: a loop that spends its budget on the last step when the fault is in an "
        "earlier one, and a memory kill treated as an infrastructure problem.",
        "- **My harness and benchmark**: a profile note that invited deleting real rows, two validation "
        "rules that were too strict (both fixed), and a task whose text disagrees with its own answer.",
        "",
    ]
    for category in order:
        rows = by_category[category]
        note = notes.get(category, {})
        example = _example(rows)
        tasks = Counter(f.task for f in rows)
        arms = Counter(f.arm for f in rows)
        lines += [
            f"## {TITLES.get(category, category)}",
            "",
            f"**{len(rows)} runs.** Tasks: " + ", ".join(f"{t} ({n})" for t, n in tasks.most_common()) + ".",
            "Arms: " + ", ".join(f"{a} ({n})" for a, n in arms.most_common()) + ".",
            "",
            note.get("means", ""),
            "",
            f"Example, `{example.run_id}` in `{example.grid}`:",
            "",
            "```",
            example.detail.strip()[:600],
            "```",
            "",
        ]
        if example.diagnosis:
            lines += [f"What the code did: {example.diagnosis}", ""]
        if note.get("fix"):
            lines += [f"**What would fix it.** {note['fix']}", ""]
    lines += [
        "## What this list changes",
        "",
        "1. A memory kill from the step's own code should reach the Reviser, not the infrastructure retry.",
        "2. The Reviser should be able to reopen the step that owns a file the delivery check complains "
        "about, or rewrite the pipeline as a whole.",
        "3. The profiler should present a duplicate count as something to check, not a defect to remove.",
        "4. The bank-2 task text must be corrected to match its own answer.",
        "5. Nothing in the loop addresses the largest class: the model is not good enough. A comparison "
        "against a simple baseline model, inside the run, would at least let the team know.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("grids", nargs="+")
    parser.add_argument("--cases", default="outputs/trust/t12")
    args = parser.parse_args()
    root = Path(args.cases)
    cases = json.loads((root / "answer_cases.json").read_text())
    notes = json.loads((root / "notes.json").read_text())
    Path("docs/failure_taxonomy.md").write_text(build([Path(g) for g in args.grids], cases, notes))
    print("wrote docs/failure_taxonomy.md")


if __name__ == "__main__":
    main()
